name: my first CI/CD
on:
  push:
     branches: [ main ]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       
       - name: Login to Docker Hub
         run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }} --password-stdin
        
       - name: Buide Docker Image
         run: docker build -t shannudocker@02/myapp .

       - name: Push to Docker Hub
         run: docker push shannudocker02/myapp
         
