name: my first CI/CD
on:
  push:
     branches: [ main ]
jobs:
  build:
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v3
       
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
        
       - name: Build Docker Image
         run: docker build -t shannudocker02/myapp .

       - name: Push to Docker Hub
         run: docker push shannudocker02/myapp
         
       - name: Deploy to EC2
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ubuntu
           key: ${{ secrets.EC2_SSH_KEY }}
           script:
              sudo docker stop ${sudo docker ps -q) || true
              sudo docker rm $(sudo docker ps -aq) || true
              sudo docker pull shannudocker02/myapp
              sudo docker run -d -p 5000:5000 shannudocker02/myapp
         
