name: my first CI/CD
on:
  push:
     branches: [ main ]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Buide Docker Image
         run: docker build -t myapp .
